steps:
  - id: install
    name: node:20
    timeout: 300s
    entrypoint: npm
    args: ['ci']

  - id: publish
    name: node:20
    entrypoint: bash
    args:
      - '-c'
      - |
        npm run artifactregistry-login
        npm publish
