steps:
  - id: install
    name: node:20
    timeout: 300s
    entrypoint: npm
    args: ["ci"]

  - id: publish
    name: node:20
    entrypoint: bash
    args:
      - "-c"
      - |
        ! [[ "$BRANCH_NAME" =~ ^(fix/increase-time-between-thread-starts)$ ]] && exit 0
        npm run artifactregistry-login
        npm publish
